name: Extras
version: '1.0'
main: net.eloxad.extras.Extras
api-version: '1.21'
commands:
  invsee:
    description: InvSee
    usage: /invsee <player>
    aliases:
      - invview
      - invsee
    permission: extras.invsee

permissions:
  extras.invsee:
    description: InvSee
    default: op